INSERT INTO cities (name, country, image) VALUES ('Lisbon', 'Portugal', 'https://www.deliciousmagazine.co.uk/wp-content/uploads/2019/07/lisbon.jpg')
INSERT INTO cities (name, country, image) VALUES ('Barcelona', 'Spain', 'https://www.healtheuropa.eu/wp-content/uploads/2020/01/iStock-TomasSereda-696x392.jpg')
INSERT INTO cities (name, country, image) VALUES ('New York City', 'USA', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRx71gFwQwOkRf74ely2el5RpyfQ8yGOzB-1Q&usqp=CAU')
INSERT INTO cities (name, country, image) VALUES ('London', 'England', 'https://imageproxy.themaven.net//https%3A%2F%2Fwww.history.com%2F.image%2FMTYyNDg1MjE3MTI1Mjc5Mzk4%2Ftopic-london-gettyimages-760251843-promo.jpg')
INSERT INTO cities (name, country, image) VALUES ('Rio de Janeiro', 'Brasil', 'https://cdn.kimkim.com/files/a/content_articles/featured_photos/67e29f693c4419341c375d333e11c210955cf3dc/big-4961ddd185dc668d672a13b52b6fe90f.jpg')
INSERT INTO cities (name, country, image) VALUES ('Rome', 'Italy', 'https://www.fodors.com/wp-content/uploads/2018/10/HERO_UltimateRome_Hero_shutterstock789412159.jpg')
INSERT INTO cities (name, country, image) VALUES ('Paris', 'France', 'https://www.fodors.com/wp-content/uploads/2018/10/HERO_UltimateParis_Heroshutterstock_112137761.jpg')
INSERT INTO cities (name, country, image) VALUES ('Berlin', 'Germany', 'https://www.steigenberger.com/cache/images/berlin_fotolia_93887_2206ae4123b62425d56a38c.jpg')
INSERT INTO cities (name, country, image) VALUES ('Tokyo', 'Japan', 'https://i.insider.com/5d26280921a86107bb51bd92?width=600&format=jpeg&auto=webp')
INSERT INTO cities (name, country, image) VALUES ('Buenos Aires', 'Argentina', 'https://www.remessaonline.com.br/blog/wp-content/uploads/2020/04/Compras-em-Buenos-Aires-veja-o-que-%C3%A9-vantajoso-comprar-na-Argentina_559272994.jpg')
INSERT INTO cities (name, country, image) VALUES ('Istanbul', 'Turkey', 'https://www.costacruises.com/content/dam/costa/inventory-assets/ports/IST/ist-istanbul-port-2.jpg')
INSERT INTO cities (name, country, image) VALUES ('Dubay', 'UAE', 'https://emerging-europe.com/wp-content/uploads/2019/11/bigstock-dubai-united-arab-emirates-307909138.jpg')
INSERT INTO cities (name, country, image) VALUES ('Amsterdam', 'Netherlands', 'https://media.timeout.com/images/105657445/image.jpg')
INSERT INTO cities (name, country, image) VALUES ('Sidney', 'Australia', 'https://www.cunard.com/content/dam/cunard/inventory-assets/ports/SYD/yqy.jpg.1538745208398.image.750.563.low.jpg')
INSERT INTO cities (name, country, image) VALUES ('Beijing', 'China', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/14/10/2d/f1/beijing.jpg?w=1100&h=600&s=1')
INSERT INTO cities (name, country, image) VALUES ('Santiago', 'Chile', 'https://thumbs.web.sapo.io/?W=800&H=0&delay_optim=1&epic=NDNmjWFbxkVxoXbTbP1EZ7YG66Tg9Bg4Rd9lc7+S74U/Y3/5LiRhpeQJFvXrweRVYyQNQTS9EeW+F7o7b5CcDBOzqEG583+fSsaBYw0jfY9b5O0=')
INSERT INTO cities (name, country, image) VALUES ('San Francisco', 'USA', 'https://www.visiteosusa.com.br/sites/default/files/styles/hero_l_x2/public/images/hero_media_image/2016-10/Getty_591648687_Brand_City_SanFrancisco_Hero_FinalCrop.jpg?itok=_WhfvSLL')
INSERT INTO cities (name, country, image) VALUES ('Bali', 'Indonesia', 'https://img.jakpost.net/c/2019/03/19/2019_03_19_67991_1552969698._large.jpg')
INSERT INTO cities (name, country, image) VALUES ('Chefchaouen', 'Morroco', 'https://assets.kpmg/content/dam/kpmg/xx/images/2019/08/blue-washed-buildings-morocco.jpg/jcr:content/renditions/cq5dam.web.512.341.jpg')
INSERT INTO cities (name, country, image) VALUES ('Singapore', 'Singapore', 'https://thumbor.forbes.com/thumbor/fit-in/1200x0/filters%3Aformat%28jpg%29/https%3A%2F%2Fblogs-images.forbes.com%2Falexcapri%2Ffiles%2F2018%2F09%2FSingapore-1200x800.jpg')
